---
title: "Schedule (subject to change)"
subtitle: "WILD8370: Bayesian Models for Conservation Science"
author: "Spring 2025"
output: 
  rmarkdown::html_vignette:
    keep_md: yes
vignette: >
  %\VignetteIndexEntry{Schedule}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  collapse = TRUE, warning = FALSE, message = FALSE,
  comment = "#>"
)

source(here::here("R/MWF.R"))
```


```{r schedule, echo = FALSE}
library(kableExtra)

schedule <- data.frame(WK = c("1", "", "", 
                              "2", "", "", 
                              "3", "", "",  
                              "4", "", "", 
                              "5", "", "", 
                              "6", "", "",  
                              "7", "", "", 
                              "8", "", "", 
                              "9", "", "", 
                              "10", "", "", 
                              "11", "", "", 
                              "12", "", "", 
                              "13", "", "",  
                              "14", "", "",  
                              "15", "", "",  
                              "16", "", "",  
                              "17"),
                       Day = c(rep(c("M", "W", ""), 16), "M"),
                       Week = MW(first.day = "2025/01/06", last.day = "2025/04/28"),
                       Lecture = c("Course Introduction", "Introduction to Statistics", "", #1
      "Probability Refresher", "Probability Refresher", "", #2
      "Principles of Bayesian Inference", "Principles of Bayesian Inference", "", #3
      "Introduction to Linear Models and Nimble", "Generalized Linear Model Review", "", #4
      "Random vs. fixed effects in Linear models", "Informative Priors", "", #5
      "Observation error, intro to hierarchical models", "Observation error, intro to hierarchical models", "", #6
      "Estimating occupancy from presence/absence data", "Abundance from N-mixture models", "", #7
      "Zero-inflated models", "Different types of observation processes", "", #8 
      "Spring Break - No Class", "Spring Break - No Class", "", #9
      "Known Fate", "Simple Movement Models", "", #10
      "Closed-population mark-recapture", "Closed-population mark-recapture", "", #11
      "CJS models", "CJS models", "", #12
      "Jolly-Seber models", "Jolly-Seber models", "", #13
      "Multi-state CMR", "Multi-state CMR", "", #14 
      "Spatial Capture Recapture", "Spatial Capture Recapture", "", #15
      "TBD", "", "", #16
      ""), 
                       Lab = c("", "Using R Markdown/Common Mathematical Notation", "",
                               "", "Data simulation techniques", "", 
                               "", "Basic MCMC", "",
                               "", "Regression analysis using Nimble", "", 
                               "", "Choosing Priors", "",
                               "", "Prior Predictive Checks", "", #be sure to include something about transformed priors
                               "", "Solving Nimble errors", "", 
                               "", "Lab 8", "",
                               "", "", "", # Spring break
                               "", "Imputing Missing Information", "",
                               "", "Simple Model Selection and CMR", "", 
                               "", "Survival Models with Detection Error", "", 
                               "", "Lab 12", "",
                               "", "Lab 13", "", 
                               "", "Lab 14", "", 
                               "", "Lab 15", "",
                               ""),
                       Notes = c("", "", "",
                               "", "", "", 
                               "", "", "", 
                               "", "", "", 
                               "", "",  "",
                                "", "",  "",
                               "",  "", "",
                               "",  "", "",
                               "", "",  "",
                               "", "",  "",
                               "", "",  "",
                               "", "",   "",
                               "", "", "", 
                               "", "", "", 
                               "", "", "", 
                               "", "", "",
                               ""))

schedule %>%
  kable("html", col.names = c("Week", "", "Date", "Lecture topic", "Lab topic", "Notes"), align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = TRUE)

```
